### PR TITLE
Migrate to typescript sdk

### PR DESCRIPTION
**Pull request by Simply007**
Internal link:
- https://kentico.atlassian.net/browse/CM-8367

- rewritten Client,js to Delivery client
- rewritten Stores to use this client
- removed closure optimization that stored already created promises, because it was never used - confirmed with jiris
- removed section for media gallery - it is not used and caused error when building to production package (contained empty url as a value)

### CODE REVIEW

**Comment by petrsvihlik** [comment]
@ChristopherJennings feel free to do the review if you get to it sooner than me :) thx

**Comment by petrsvihlik** [comment]
Unfortunately, there are some extra steps required because of https://github.com/Kentico/cloud-sample-app-js/pull/11 .

1) We need to update the TS SDK with the Taxonomy groups endpoint https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/issues/20
2) Reference the new version of TS SDK from cloud-sample-app-js (this repo)
3) Update the taxonomy groups-dependent code to use the SDK (== resolve the conflicts here)

**Comment by petrsvihlik** [comment]
thanks @Simply007 ...Chris or I will have a look at it soon

**Comment by ChristopherJennings** [comment]
Reviewed the code changes nothing stood out as problematic. All previous functionality appears to be preserved and working. Thanks for the effort!

**Pull request merged**
